# Name your project!
name: 'shopflow_dbt'
version: '1.0.0'

# Profile
profile: 'shopflow_dbt'

# Paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Models configuration
models:
  shopflow_dbt:
    bronze:
      +materialized: table
      +schema: bronze

    silver:
      +materialized: table
      +schema: silver

    gold:
      +materialized: table
      +schema: gold